# Generated by Django 3.1.6 on 2021-06-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin1',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('Asset_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(choices=[('Select', 'Select'), ('Food', 'Food'), ('Stationary', 'Stationary'), ('Money', 'Money'), ('Furniture', 'Furniture')], default='Select', max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Cost', models.CharField(max_length=10)),
                ('Quantity', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False, max_length=50)),
                ('Added_date', models.DateField(auto_now_add=True)),
                ('Updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DonorID', models.PositiveIntegerField(null=True)),
                ('Type', models.CharField(choices=[('Select', 'Select'), ('Food', 'Food'), ('Stationary', 'Stationary'), ('Money', 'Money'), ('Furniture', 'Furniture')], default='Select', max_length=50)),
                ('Amount', models.CharField(max_length=20)),
                ('Donate_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Gender', models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='Select', max_length=255)),
                ('Occupation', models.CharField(max_length=25, null=True)),
                ('Contact_No', models.CharField(max_length=11, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('Created_date', models.DateField(auto_now_add=True)),
                ('Updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('ExpenceID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(choices=[('Select', 'Select'), ('Purchases', 'Purchases'), ('Salary', 'Salary'), ('Bill', 'Bill'), ('Medicines', 'Medicines'), ('Education', 'Education'), ('Others', 'Others')], default='Select', max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Amount', models.CharField(max_length=10)),
                ('Bill_No', models.CharField(max_length=50)),
                ('Bill_File', models.FileField(max_length=255, upload_to='bills/')),
                ('Date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, max_length=50)),
                ('Added_date', models.DateField(auto_now_add=True)),
                ('Updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oldage',
            fields=[
                ('OldID', models.IntegerField(primary_key=True, serialize=False)),
                ('Old_Name', models.CharField(max_length=255)),
                ('Gender', models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female')], default='Select', max_length=255)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Age', models.CharField(max_length=10)),
                ('Bgroup', models.CharField(max_length=50)),
                ('Nominee', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False, max_length=50)),
                ('Created_date', models.DateField(auto_now_add=True)),
                ('Updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orphans',
            fields=[
                ('OrphanID', models.IntegerField(primary_key=True, serialize=False)),
                ('Orphan_Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('Select the gender', 'Select the gender'), ('Male', 'Male'), ('Female', 'Female')], default='Select', max_length=50)),
                ('DOB', models.CharField(max_length=50)),
                ('Bgroup', models.CharField(max_length=50)),
                ('Standard', models.CharField(max_length=50)),
                ('Nominee', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False, max_length=50)),
                ('Created_date', models.DateField(auto_now_add=True)),
                ('Updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('Adopt_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('DonorID', models.PositiveIntegerField(null=True)),
                ('Adopte', models.BooleanField(default=False, max_length=20)),
                ('OrphanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showhope.orphans')),
            ],
        ),
    ]
