# Generated by Django 3.1.6 on 2021-06-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showhope', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='donorName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
