# Generated by Django 3.1.6 on 2021-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showhope', '0005_payment_donorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='OrphanID',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
